### ISSUE TITLE
Manually generated scm-source.json

### ISSUE THREAD

**Issue by bocytko** [zalando/saiki-pemetaan#1]
Why do you use a custom [script](https://github.com/zalando/saiki-pemetaan/blob/master/create_scm_source.sh) for generating `scm-source.json`? How about using [scm-source](https://pypi.python.org/pypi/scm-source) like in [zmon-scheduler](https://github.com/zalando/zmon-scheduler) instead?

**Comment by drummerwolli** [comment]
was not aware of such a package. i basically copied the instructions from the stups docu and the pypi package was not available when i first read about that last summer. thx for the hint ...
